const KEY='fitplanner.v1';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const todayISO=()=>new Date().toISOString().slice(0,10);
const uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
const fmtDate=iso=>new Intl.DateTimeFormat('el-GR',{day:'numeric',month:'long',year:'numeric'}).format(new Date(iso+'T12:00:00'));

const starterPrograms=[
 {id:'fullbody-dumbbells-beginner',title:'Ολόκληρο σώμα με βαράκια — Αρχάριος',place:'home',level:'beginner',duration:40,goal:'general',exercises:[['Καθίσματα κρατώντας βαράκι στο στήθος',3,10],['Πιέσεις στήθους με βαράκια στο πάτωμα',3,10],['Κωπηλατική με ένα βαράκι',3,10],['Άρσεις θανάτου με βαράκια και τεντωμένα πόδια',3,10],['Σανίδα',3,30]]},
 {id:'bodyweight-20',title:'Ασκήσεις με το βάρος του σώματος — 20 λεπτά',place:'home',level:'beginner',duration:20,goal:'fatloss',exercises:[['Καθίσματα',3,12],['Κάμψεις',3,8],['Προβολές ποδιών',3,10],['Γέφυρες γλουτών',3,15],['Ορειβάτες',4,30]]},
 {id:'upper-dumbbells',title:'Άνω σώμα με βαράκια',place:'home',level:'intermediate',duration:45,goal:'muscle',exercises:[['Πιέσεις στήθους με βαράκια',4,10],['Κωπηλατική σκυφτός με βαράκια',4,10],['Πιέσεις ώμων με βαράκια',3,10],['Πλάγιες άρσεις ώμων με βαράκια',3,12],['Κάμψεις δικεφάλων με βαράκια',3,12],['Εκτάσεις τρικεφάλων πάνω από το κεφάλι',3,12]]},
 {id:'lower-dumbbells',title:'Πόδια και γλουτοί με βαράκια',place:'home',level:'intermediate',duration:45,goal:'strength',exercises:[['Καθίσματα κρατώντας βαράκια',4,10],['Προβολές με βαράκια',3,10],['Άρσεις θανάτου με βαράκια',4,10],['Ανεβάσματα σε σκαλοπάτι με βαράκια',3,10],['Γέφυρες γλουτών με βαράκι',3,15],['Άρσεις γάμπας κρατώντας βαράκια',4,15]]},
 {id:'fullbody-strength',title:'Δύναμη ολόκληρου σώματος με βαράκια',place:'home',level:'intermediate',duration:50,goal:'strength',exercises:[['Καθίσματα με βαράκια',4,8],['Πιέσεις στήθους με βαράκια',4,8],['Κωπηλατική με βαράκια',4,8],['Πιέσεις ώμων με βαράκια',3,8],['Άρσεις θανάτου με βαράκια',4,8],['Σανίδα με άγγιγμα ώμων',3,20]]},
 {id:'bodyweight-full',title:'Ολόκληρο σώμα χωρίς εξοπλισμό',place:'home',level:'beginner',duration:35,goal:'general',exercises:[['Καθίσματα',4,12],['Κάμψεις σε τοίχο ή γόνατα',3,10],['Προβολές προς τα πίσω',3,10],['Βυθίσεις τρικεφάλων σε καρέκλα',3,8],['Γέφυρες γλουτών',3,15],['Σανίδα',3,30]]},
 {id:'core-bodyweight',title:'Κοιλιακοί και κορμός με βάρος σώματος',place:'home',level:'beginner',duration:25,goal:'general',exercises:[['Σανίδα',3,30],['Πλάγια σανίδα',3,20],['Άρσεις αντίθετου χεριού και ποδιού',3,10],['Νεκρό έντομο',3,10],['Ορειβάτες',3,30],['Άρσεις λεκάνης',3,15]]},
 {id:'conditioning-dumbbells',title:'Κυκλική προπόνηση με βαράκια',place:'home',level:'intermediate',duration:30,goal:'endurance',exercises:[['Καθίσματα και πίεση ώμων με βαράκια',4,10],['Κωπηλατική με βαράκια',4,10],['Προβολές εναλλάξ',4,10],['Κάμψεις',4,8],['Άρσεις θανάτου με βαράκια',4,10],['Ορειβάτες',4,30]]},
 {id:'mobility',title:'Κινητικότητα και αποκατάσταση',place:'home',level:'beginner',duration:25,goal:'mobility',exercises:[['Κίνηση γάτας και αγελάδας',2,10],['Περιστροφές ισχίων 90/90',2,8],['Περιστροφές θωρακικής μοίρας',2,8],['Διάταση καμπτήρων ισχίου',2,40],['Στάση του παιδιού',2,45]]},
 {id:'superset-fullbody-1',title:'Superset ολόκληρου σώματος με βαράκια',place:'gym',level:'intermediate',duration:35,goal:'general',exercises:[['Καθίσματα με βαράκια + Πιέσεις ώμων',4,10],['Κωπηλατική με βαράκια + Κάμψεις',4,10],['Άρσεις θανάτου με βαράκια + Ορειβάτες',4,10],['Προβολές με βαράκια + Σανίδα',3,10]]},
 {id:'superset-upper-1',title:'Superset άνω σώματος',place:'gym',level:'intermediate',duration:35,goal:'muscle',exercises:[['Πιέσεις στήθους με βαράκια + Κωπηλατική με βαράκια',4,10],['Πιέσεις ώμων + Πλάγιες άρσεις ώμων',3,10],['Κάμψεις δικεφάλων + Εκτάσεις τρικεφάλων',3,12],['Κάμψεις + Σανίδα με άγγιγμα ώμων',3,10]]},
 {id:'superset-lower-1',title:'Superset ποδιών και γλουτών',place:'gym',level:'intermediate',duration:35,goal:'strength',exercises:[['Καθίσματα με βαράκια + Άρσεις θανάτου με βαράκια',4,10],['Προβολές προς τα πίσω + Γέφυρες γλουτών',3,12],['Ανεβάσματα σε σκαλοπάτι + Άρσεις γάμπας',3,12],['Καθίσματα χωρίς βάρος + Σανίδα',3,15]]}
];

let state=load();
let calDate=new Date();
let selectedDate=todayISO();
let activeFilter='all';

function defaultState(){
 const id=uid();
 return {activePersonId:id,theme:'light',people:[{id,name:'Αλέξανδρος',birthdate:'',sex:'',height:'',weight:'',waist:'',level:'beginner',place:'gym',days:3,duration:45,goal:'general',limitations:'',measurements:[],calendar:{},customPrograms:[]}]} ;
}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||defaultState()}catch{return defaultState()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
function person(){return state.people.find(p=>p.id===state.activePersonId)||state.people[0]}
function ageOf(b){if(!b)return null;const d=new Date(b),n=new Date();let a=n.getFullYear()-d.getFullYear();if(n<new Date(n.getFullYear(),d.getMonth(),d.getDate()))a--;return a}
function latestMeasurement(p){return [...(p.measurements||[])].filter(m=>m.date&&m.weight).sort((a,b)=>b.date.localeCompare(a.date))[0]||null}
function currentWeightOf(p){const m=latestMeasurement(p);return m?String(m.weight):String(p.weight||'')}
function syncCurrentMeasurement(p){const m=latestMeasurement(p);if(m){p.weight=String(m.weight);if(m.waist)p.waist=String(m.waist)}}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function go(view){$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===view));$$('[data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go===view));if(view==='profile')fillProfile();if(view==='calendar')renderCalendar();window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));

function renderAll(){
 document.body.classList.toggle('dark',state.theme==='dark');
 const p=person();syncCurrentMeasurement(p);
 $('#activeName').textContent=p.name;
 $('#activeAvatar').textContent=(p.name||'?')[0].toUpperCase();
 const bits=[]; const age=ageOf(p.birthdate); if(age)bits.push(age+' ετών'); if(p.height)bits.push(p.height+' cm'); const cw=currentWeightOf(p); if(cw)bits.push(cw+' kg');
 $('#activeSummary').textContent=bits.join(' • ')||'Δεν έχουν συμπληρωθεί στοιχεία';
 $('#currentWeight').textContent=cw?cw+' kg':'—';
 const month=todayISO().slice(0,7); const entries=Object.entries(p.calendar||{}).filter(([d])=>d.startsWith(month)).flatMap(([,a])=>a||[]);
 $('#monthWorkouts').textContent=entries.filter(e=>e.done).length;
 $('#streak').textContent=calcStreak(p)+' εβδομ.';
 $('#nextGoal').textContent=goalName(p.goal);
 renderPeople();renderPrograms();renderMeasurements();renderHomeToday();
}
function calcStreak(p){let s=0;for(let w=0;w<12;w++){const end=new Date();end.setDate(end.getDate()-w*7);const start=new Date(end);start.setDate(end.getDate()-6);const has=Object.entries(p.calendar||{}).some(([d,a])=>{const x=new Date(d+'T12:00:00');return x>=start&&x<=end&&(a||[]).some(e=>e.done)});if(has)s++;else if(w>0)break;}return s}
function goalName(g){return ({general:'Ευεξία',fatloss:'Απώλεια λίπους',muscle:'Μυϊκή ανάπτυξη',strength:'Δύναμη',endurance:'Αντοχή',mobility:'Κινητικότητα'})[g]||'Ορισμός'}
function renderHomeToday(){const a=(person().calendar||{})[todayISO()]||[];if(a.length){$('#todayTitle').textContent=a[0].title;$('#todaySubtitle').textContent=a[0].done?'Η προπόνηση ολοκληρώθηκε.':'Έχει προγραμματιστεί για σήμερα.';$('#startTodayBtn').textContent=a[0].done?'Προβολή':'Ξεκίνα προπόνηση'}else{$('#todayTitle').textContent='Η σημερινή προπόνηση';$('#todaySubtitle').textContent='Δημιούργησε πρόγραμμα ή πάρε αυτόματη πρόταση.';$('#startTodayBtn').textContent='Ξεκίνα προπόνηση'}}

function renderPeople(){const g=$('#peopleGrid');g.innerHTML='';state.people.forEach(p=>{const el=document.createElement('article');el.className='person-card card';el.innerHTML=`<div class="person-head"><div class="profile-avatar">${(p.name||'?')[0]}</div><div><h3>${esc(p.name)}</h3><div class="muted small">${[ageOf(p.birthdate)?ageOf(p.birthdate)+' ετών':'',p.weight?p.weight+' kg':''].filter(Boolean).join(' • ')||'Χωρίς στοιχεία'}</div></div></div><div class="actions"><button class="primary select-person">${p.id===state.activePersonId?'Ενεργό':'Επιλογή'}</button><button class="secondary edit-person">Επεξεργασία</button>${state.people.length>1?'<button class="danger delete-person">×</button>':''}</div>`;
 el.querySelector('.select-person').onclick=()=>{state.activePersonId=p.id;save();toast('Επιλέχθηκε το προφίλ')};
 el.querySelector('.edit-person').onclick=()=>{state.activePersonId=p.id;save();go('profile')};
 el.querySelector('.delete-person')?.addEventListener('click',()=>{if(confirm('Να διαγραφεί το προφίλ και όλο το ιστορικό του;')){state.people=state.people.filter(x=>x.id!==p.id);if(state.activePersonId===p.id)state.activePersonId=state.people[0].id;save()}});
 g.appendChild(el)});
}
$('#addPersonBtn').onclick=()=>openPersonModal();
function openPersonModal(){openModal(`<h2>Νέο άτομο</h2><label>Όνομα<input id="newPersonName" required autofocus></label><div class="modal-actions"><button value="cancel" class="secondary">Ακύρωση</button><button value="default" class="primary" id="createPerson">Δημιουργία</button></div>`);$('#createPerson').onclick=e=>{e.preventDefault();const name=$('#newPersonName').value.trim();if(!name)return;const p={...defaultState().people[0],id:uid(),name,calendar:{},measurements:[],customPrograms:[]};state.people.push(p);state.activePersonId=p.id;closeModal();save();go('profile')}}

function initBirthdateSelectors(){
 const day=$('#birthDay'),month=$('#birthMonth'),year=$('#birthYear');
 if(day.options.length)return;
 day.innerHTML='<option value="">Ημέρα</option>'+Array.from({length:31},(_,i)=>`<option value="${String(i+1).padStart(2,'0')}">${i+1}</option>`).join('');
 month.innerHTML='<option value="">Μήνας</option>'+['Ιανουάριος','Φεβρουάριος','Μάρτιος','Απρίλιος','Μάιος','Ιούνιος','Ιούλιος','Αύγουστος','Σεπτέμβριος','Οκτώβριος','Νοέμβριος','Δεκέμβριος'].map((x,i)=>`<option value="${String(i+1).padStart(2,'0')}">${x}</option>`).join('');
 const y=new Date().getFullYear();year.innerHTML='<option value="">Έτος</option>'+Array.from({length:100},(_,i)=>`<option value="${y-i}">${y-i}</option>`).join('');
}
function fillProfile(){const p=person(),f=$('#profileForm');initBirthdateSelectors();Object.keys(p).forEach(k=>{if(f.elements[k])f.elements[k].value=p[k]??''});const [y,m,d]=(p.birthdate||'--').split('-');$('#birthDay').value=d||'';$('#birthMonth').value=m||'';$('#birthYear').value=y||''}
$('#saveProfileBtn').onclick=()=>{const p=person(),d=$('#birthDay').value,m=$('#birthMonth').value,y=$('#birthYear').value;$('#birthdateHidden').value=(d&&m&&y)?`${y}-${m}-${d}`:'';const f=new FormData($('#profileForm'));for(const [k,v] of f.entries())p[k]=v;p.days=Number(p.days||3);p.duration=Number(p.duration||45);save();toast('Το προφίλ αποθηκεύτηκε')};

function bmiData(p){if(!p.height||!p.weight)return null;const h=Number(p.height)/100,b=Number(p.weight)/(h*h);let label=b<18.5?'Χαμηλότερο από το συνήθως ενδεικτικό εύρος':b<25?'Μέσα στο συνήθως ενδεικτικό εύρος':b<30?'Πάνω από το συνήθως ενδεικτικό εύρος':'Σημαντικά πάνω από το ενδεικτικό εύρος';return {b,low:18.5*h*h,high:24.9*h*h,label}}
function renderWeightChart(p){
 const host=$('#weightChart');if(!host)return;const list=[...(p.measurements||[])].filter(m=>m.date&&m.weight).sort((a,b)=>a.date.localeCompare(b.date));
 if(!list.length){host.innerHTML='<p class="muted">Δεν υπάρχουν αρκετές καταχωρίσεις βάρους.</p>';return}
 const W=760,H=230,pad={l:52,r:20,t:18,b:45},vals=list.map(x=>Number(x.weight)),min=Math.min(...vals),max=Math.max(...vals),spread=Math.max(1,max-min),lo=min-spread*.25,hi=max+spread*.25;
 const x=i=>pad.l+(list.length===1?(W-pad.l-pad.r)/2:i*(W-pad.l-pad.r)/(list.length-1));const y=v=>pad.t+(hi-v)*(H-pad.t-pad.b)/(hi-lo);
 let grid='';for(let i=0;i<5;i++){const yy=pad.t+i*(H-pad.t-pad.b)/4,val=hi-i*(hi-lo)/4;grid+=`<line class="chart-grid" x1="${pad.l}" y1="${yy}" x2="${W-pad.r}" y2="${yy}"/><text class="chart-label" x="4" y="${yy+4}">${val.toFixed(1)} kg</text>`}
 const pts=list.map((m,i)=>`${x(i)},${y(Number(m.weight))}`).join(' ');const dots=list.map((m,i)=>`<circle class="chart-point" cx="${x(i)}" cy="${y(Number(m.weight))}" r="6"><title>${fmtDate(m.date)}: ${m.weight} kg</title></circle><text class="chart-label" text-anchor="middle" x="${x(i)}" y="${H-18}">${m.date.split('-').reverse().slice(0,2).join('/')}</text>`).join('');
 host.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Εξέλιξη βάρους">${grid}<polyline class="chart-line" points="${pts}"/>${dots}</svg>`;
}
function renderMeasurements(){const p=person();syncCurrentMeasurement(p);const b=bmiData(p);$('#bmiValue').textContent=b?b.b.toFixed(1):'—';$('#bmiLabel').textContent=b?b.label:'Συμπλήρωσε ύψος και βάρος';$('#weightRange').textContent=b?`${b.low.toFixed(1)}–${b.high.toFixed(1)} kg`:'—';if(p.height&&p.waist){const r=Number(p.waist)/Number(p.height);$('#whrValue').textContent=r.toFixed(2);$('#whrLabel').textContent=r<.5?'Κάτω από το 0,50':'Στο 0,50 ή υψηλότερα'}else{$('#whrValue').textContent='—';$('#whrLabel').textContent='Πρόσθεσε περίμετρο μέσης'}renderWeightChart(p);const h=$('#measurementHistory');h.innerHTML='';const list=[...(p.measurements||[])].sort((a,b)=>b.date.localeCompare(a.date));if(!list.length)h.innerHTML='<p class="muted">Δεν υπάρχουν καταχωρίσεις.</p>';list.forEach(m=>{const e=document.createElement('div');e.className='entry';e.innerHTML=`<div class="grow"><b>${fmtDate(m.date)}</b><span class="muted small">${m.weight?m.weight+' kg':''}${m.waist?' • Μέση '+m.waist+' cm':''}${m.chest?' • Στήθος '+m.chest+' cm':''}</span></div><button class="secondary edit-measurement">Επεξεργασία</button><button class="danger delete-measurement">×</button>`;e.querySelector('.edit-measurement').onclick=()=>openMeasurementModal(m);e.querySelector('.delete-measurement').onclick=()=>{p.measurements=p.measurements.filter(x=>x.id!==m.id);syncCurrentMeasurement(p);save()};h.appendChild(e)})}
function openMeasurementModal(existing=null){const m=existing||{date:todayISO(),weight:currentWeightOf(person()),waist:person().waist||'',chest:'',arm:'',thigh:''};openModal(`<h2>${existing?'Επεξεργασία μέτρησης':'Νέα μέτρηση'}</h2><div class="form-grid"><label>Ημερομηνία<input id="mDate" type="date" value="${m.date||todayISO()}"></label><label>Βάρος (kg)<input id="mWeight" type="number" step="0.1" value="${m.weight||''}"></label><label>Μέση (cm)<input id="mWaist" type="number" step="0.1" value="${m.waist||''}"></label><label>Στήθος (cm)<input id="mChest" type="number" step="0.1" value="${m.chest||''}"></label><label>Μπράτσο (cm)<input id="mArm" type="number" step="0.1" value="${m.arm||''}"></label><label>Μηρός (cm)<input id="mThigh" type="number" step="0.1" value="${m.thigh||''}"></label></div><div class="modal-actions"><button value="cancel" class="secondary">Ακύρωση</button><button class="primary" id="saveMeasurement">Αποθήκευση</button></div>`);$('#saveMeasurement').onclick=e=>{e.preventDefault();const p=person(),data={id:existing?.id||uid(),date:$('#mDate').value,weight:$('#mWeight').value,waist:$('#mWaist').value,chest:$('#mChest').value,arm:$('#mArm').value,thigh:$('#mThigh').value};if(existing)Object.assign(existing,data);else p.measurements.push(data);syncCurrentMeasurement(p);closeModal();save();toast('Η μέτρηση αποθηκεύτηκε')}}
$('#addMeasurementBtn').onclick=()=>openMeasurementModal();

function allPrograms(){return [...starterPrograms,...(person().customPrograms||[])]}
function renderPrograms(){const g=$('#programGrid');g.innerHTML='';allPrograms().filter(p=>activeFilter==='all'||p.place===activeFilter||p.level===activeFilter).forEach(p=>{const el=document.createElement('article');el.className='program-card card';el.innerHTML=`<span class="tag">${p.place==='home'?'Σπίτι':'Γυμναστήριο'}</span><span class="tag">${p.duration}′</span><h3>${esc(p.title)}</h3><ul>${p.exercises.slice(0,5).map(x=>`<li><button type="button" class="exercise-link" data-exercise="${encodeURIComponent(x[0])}">${esc(x[0])}</button> — ${x[1]} × ${x[2]}</li>`).join('')}</ul><div class="actions"><button class="primary use-program">Προγραμματισμός</button><button class="secondary view-program">Προβολή</button></div>`;el.querySelector('.use-program').onclick=()=>scheduleProgram(p);el.querySelector('.view-program').onclick=()=>viewProgram(p);el.querySelectorAll('.exercise-link').forEach(b=>b.onclick=()=>showExercise(decodeURIComponent(b.dataset.exercise)));g.appendChild(el)})}
$$('.chip').forEach(c=>c.onclick=()=>{$$('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active');activeFilter=c.dataset.filter;renderPrograms()});
function viewProgram(p){openModal(`<h2>${esc(p.title)}</h2><p class="muted">${p.duration} λεπτά • ${p.place==='home'?'Σπίτι':'Γυμναστήριο'}</p><div class="stack">${p.exercises.map(x=>`<div class="entry"><div class="grow"><button type="button" class="exercise-link" data-exercise="${encodeURIComponent(x[0])}">${esc(x[0])}</button><span class="muted small">${x[1]} σετ × ${x[2]} ${Number(x[2])>20?'δευτ.':'επαν.'}</span></div></div>`).join('')}</div><div class="modal-actions"><button value="cancel" class="secondary">Κλείσιμο</button><button class="primary" id="scheduleFromView">Προγραμματισμός</button></div>`);$('#modalContent').querySelectorAll('.exercise-link').forEach(b=>b.onclick=()=>showExercise(decodeURIComponent(b.dataset.exercise),true));$('#scheduleFromView').onclick=e=>{e.preventDefault();closeModal();scheduleProgram(p)}}
function scheduleProgram(p,date=selectedDate){openModal(`<h2>Προγραμματισμός</h2><label>Ημερομηνία<input id="scheduleDate" type="date" value="${date||todayISO()}"></label><div class="modal-actions"><button value="cancel" class="secondary">Ακύρωση</button><button class="primary" id="confirmSchedule">Αποθήκευση</button></div>`);$('#confirmSchedule').onclick=e=>{e.preventDefault();const d=$('#scheduleDate').value,per=person();per.calendar[d]=per.calendar[d]||[];per.calendar[d].push({id:uid(),programId:p.id,title:p.title,done:false,exercises:p.exercises.map(x=>[...x])});closeModal();save();selectedDate=d;toast('Μπήκε στο ημερολόγιο')}}
$('#newProgramBtn').onclick=()=>openProgramBuilder();
function openProgramBuilder(){openModal(`<h2>Νέο πρόγραμμα</h2><label>Όνομα<input id="progTitle"></label><div class="form-grid"><label>Χώρος<select id="progPlace"><option value="gym">Γυμναστήριο</option><option value="home">Σπίτι</option></select></label><label>Διάρκεια<input id="progDuration" type="number" value="45"></label></div><h3>Ασκήσεις</h3><div id="exerciseBuilder"></div><button type="button" class="secondary" id="addExercise">+ Άσκηση</button><div class="modal-actions"><button value="cancel" class="secondary">Ακύρωση</button><button class="primary" id="saveProgram">Αποθήκευση</button></div>`);const add=()=>{const r=document.createElement('div');r.className='exercise-row';r.innerHTML='<input placeholder="Άσκηση"><input type="number" value="3" min="1"><input type="number" value="10" min="1"><button type="button" class="danger">×</button>';r.querySelector('button').onclick=()=>r.remove();$('#exerciseBuilder').appendChild(r)};add();add();add();$('#addExercise').onclick=add;$('#saveProgram').onclick=e=>{e.preventDefault();const exercises=$$('#exerciseBuilder .exercise-row').map(r=>{const i=r.querySelectorAll('input');return[i[0].value.trim(),Number(i[1].value),Number(i[2].value)]}).filter(x=>x[0]);if(!$('#progTitle').value.trim()||!exercises.length)return;person().customPrograms.push({id:uid(),title:$('#progTitle').value.trim(),place:$('#progPlace').value,level:person().level,duration:Number($('#progDuration').value),goal:person().goal,exercises});closeModal();save();toast('Το πρόγραμμα δημιουργήθηκε')}}

function suggestProgram(){const p=person();let candidates=starterPrograms.filter(x=>(p.place==='both'||x.place===p.place)&&(x.level===p.level||p.level==='advanced'));if(!candidates.length)candidates=starterPrograms;let pick=candidates.find(x=>x.goal===p.goal)||candidates[0];viewProgram(pick)}
$('#suggestBtn').onclick=suggestProgram;$('#startTodayBtn').onclick=()=>{const a=(person().calendar||{})[todayISO()]||[];if(a.length)openWorkout(a[0],todayISO());else suggestProgram()};

function renderCalendar(){const y=calDate.getFullYear(),m=calDate.getMonth();$('#calendarMonth').textContent=new Intl.DateTimeFormat('el-GR',{month:'long',year:'numeric'}).format(calDate);const first=new Date(y,m,1),offset=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),prevDays=new Date(y,m,0).getDate(),g=$('#calendarGrid');g.innerHTML='';for(let i=0;i<42;i++){let d,mon=m,yr=y,out=false;if(i<offset){d=prevDays-offset+i+1;mon=m-1;out=true}else if(i>=offset+days){d=i-offset-days+1;mon=m+1;out=true}else d=i-offset+1;const dt=new Date(yr,mon,d),iso=[dt.getFullYear(),String(dt.getMonth()+1).padStart(2,'0'),String(dt.getDate()).padStart(2,'0')].join('-');const b=document.createElement('button');b.className='day'+(out?' out':'')+(iso===todayISO()?' today':'')+(iso===selectedDate?' selected':'');b.innerHTML=`<span>${d}</span>${(person().calendar[iso]||[]).length?'<i class="dot"></i>':''}`;b.onclick=()=>{selectedDate=iso;renderCalendar()};g.appendChild(b)}renderDayPanel()}
function renderDayPanel(){ $('#selectedDateTitle').textContent=fmtDate(selectedDate);const a=person().calendar[selectedDate]||[],g=$('#dayEntries');g.innerHTML='';if(!a.length)g.innerHTML='<p class="muted">Δεν υπάρχει προγραμματισμένη προπόνηση.</p>';a.forEach(e=>{const row=document.createElement('div');row.className='entry'+(e.done?' done':'');row.innerHTML=`<div class="grow"><b>${esc(e.title)}</b><span class="muted small">${e.done?'Ολοκληρώθηκε':'Προγραμματισμένη'}</span></div><button class="primary">${e.done?'Προβολή':'Έναρξη'}</button><button class="danger">×</button>`;row.querySelector('.primary').onclick=()=>openWorkout(e,selectedDate);row.querySelector('.danger').onclick=()=>{person().calendar[selectedDate]=a.filter(x=>x.id!==e.id);save();renderCalendar()};g.appendChild(row)})}
$('#prevMonth').onclick=()=>{calDate.setMonth(calDate.getMonth()-1);renderCalendar()};$('#nextMonth').onclick=()=>{calDate.setMonth(calDate.getMonth()+1);renderCalendar()};$('#calendarTodayBtn').onclick=()=>{calDate=new Date();selectedDate=todayISO();renderCalendar()};$('#addDayWorkoutBtn').onclick=()=>{go('programs')};
function openWorkout(entry,date){
 entry.exercises=entry.exercises||[];openModal(`<h2>${esc(entry.title)}</h2><p class="muted">${fmtDate(date)}</p><label>Διάρκεια προπόνησης (λεπτά)<input id="workoutDuration" type="number" min="0" value="${entry.duration||''}" placeholder="π.χ. 60"></label><h3>Ασκήσεις</h3><div id="workoutEditor" class="workout-editor"></div><button type="button" class="secondary" id="addWorkoutExercise">+ Άσκηση</button><div class="modal-actions"><button value="cancel" class="secondary">Κλείσιμο</button><button type="button" class="secondary" id="saveWorkoutChanges">Αποθήκευση αλλαγών</button><button type="button" class="primary" id="finishWorkout">${entry.done?'Αποθήκευση ως ολοκληρωμένη':'Ολοκλήρωση'}</button></div>`);
 const host=$('#workoutEditor');const addRow=(x=['',3,10])=>{const r=document.createElement('div');r.className='workout-exercise-row';r.innerHTML=`<label>Άσκηση<input class="we-name" value="${esc(x[0]||'')}"><button type="button" class="exercise-link we-image">Προβολή εικόνας</button></label><label>Σετ<input class="we-sets" type="number" min="1" value="${x[1]||3}"></label><label>Επαν.<input class="we-reps" type="number" min="1" value="${x[2]||10}"></label><button type="button" class="danger">×</button>`;r.querySelector('.danger').onclick=()=>r.remove();r.querySelector('.we-image').onclick=()=>showExercise(r.querySelector('.we-name').value);host.appendChild(r)};entry.exercises.forEach(addRow);$('#addWorkoutExercise').onclick=()=>addRow();
 const collect=()=>{entry.duration=Number($('#workoutDuration').value||0);entry.exercises=$$('#workoutEditor .workout-exercise-row').map(r=>[r.querySelector('.we-name').value.trim(),Number(r.querySelector('.we-sets').value||1),Number(r.querySelector('.we-reps').value||1)]).filter(x=>x[0]);};
 $('#saveWorkoutChanges').onclick=()=>{collect();closeModal();save();renderCalendar();toast('Οι αλλαγές αποθηκεύτηκαν')};$('#finishWorkout').onclick=()=>{collect();entry.done=true;entry.completedAt=new Date().toISOString();closeModal();save();renderCalendar();toast('Η προπόνηση αποθηκεύτηκε')};
}
function exercisePose(name){const n=name.toLowerCase();if(n.includes('κάμψ')||n.includes('πιέσεις στήθους'))return 'push';if(n.includes('κωπηλα'))return 'row';if(n.includes('καθίσ')||n.includes('προβολ'))return 'squat';if(n.includes('άρσεις θανάτου'))return 'hinge';if(n.includes('σανίδα')||n.includes('ορειβά'))return 'plank';if(n.includes('ώμων')||n.includes('πλάγιες άρσεις'))return 'press';if(n.includes('δικεφάλ'))return 'curl';if(n.includes('τρικεφάλ'))return 'triceps';if(n.includes('γέφυρ'))return 'bridge';return 'general'}
function exerciseSvg(name){const pose=exercisePose(name),base=`<svg viewBox="0 0 640 300" role="img" aria-label="Ενδεικτική εικόνα εκτέλεσης ${esc(name)}"><defs><style>.f{fill:none;stroke:currentColor;stroke-width:10;stroke-linecap:round;stroke-linejoin:round}.w{fill:var(--primary)}.t{fill:var(--muted);font:20px system-ui}</style></defs><text class="t" x="110" y="35">Αρχική θέση</text><text class="t" x="430" y="35">Τελική θέση</text>`;const fig=(x,y,kind,end)=>{if(kind==='squat')return `<circle class="f" cx="${x}" cy="${y-90}" r="22"/><path class="f" d="M${x} ${y-66} L${x+(end?18:0)} ${y-10} L${x+(end?55:25)} ${y+32} M${x+(end?18:0)} ${y-25} L${x-40} ${y+20} M${x+(end?18:0)} ${y-25} L${x+48} ${y+10}"/><circle class="w" cx="${x-43}" cy="${y+21}" r="10"/><circle class="w" cx="${x+51}" cy="${y+11}" r="10"/>`;if(kind==='push'||kind==='plank')return `<circle class="f" cx="${x-65}" cy="${y-42+(end?26:0)}" r="18"/><path class="f" d="M${x-45} ${y-35+(end?25:0)} L${x+55} ${y-5} L${x+110} ${y+18} M${x-10} ${y-25+(end?20:0)} L${x-20} ${y+35} M${x+65} ${y} L${x+45} ${y+50}"/>`;if(kind==='hinge'||kind==='row')return `<circle class="f" cx="${x-20+(end?35:0)}" cy="${y-92+(end?20:0)}" r="20"/><path class="f" d="M${x-8+(end?30:0)} ${y-70+(end?18:0)} L${x+30} ${y-20} L${x+5} ${y+45} M${x+25} ${y-25} L${x-45} ${y+20} M${x+25} ${y-25} L${x+80} ${y+20}"/><circle class="w" cx="${x-48}" cy="${y+22}" r="10"/><circle class="w" cx="${x+83}" cy="${y+22}" r="10"/>`;if(kind==='bridge')return `<circle class="f" cx="${x-75}" cy="${y+5-(end?35:0)}" r="19"/><path class="f" d="M${x-55} ${y+5-(end?35:0)} L${x+20} ${y-(end?35:0)} L${x+80} ${y+35} M${x+15} ${y-(end?35:0)} L${x-15} ${y+42}"/>`;return `<circle class="f" cx="${x}" cy="${y-90}" r="22"/><path class="f" d="M${x} ${y-65} L${x} ${y+20} M${x} ${y-35} L${x-50} ${y-(end?80:0)} M${x} ${y-35} L${x+50} ${y-(end?80:0)} M${x} ${y+20} L${x-35} ${y+80} M${x} ${y+20} L${x+35} ${y+80}"/><circle class="w" cx="${x-53}" cy="${y-(end?82:0)}" r="10"/><circle class="w" cx="${x+53}" cy="${y-(end?82:0)}" r="10"/>`};return base+fig(165,170,pose,false)+`<path class="f" d="M285 150 L355 150 M340 135 L355 150 L340 165"/>`+fig(475,170,pose,true)+`</svg>`}
function showExercise(name,fromModal=false){const previous=fromModal?$('#modalContent').innerHTML:null;openModal(`<h2>${esc(name)}</h2><div class="exercise-figure">${exerciseSvg(name)}</div><p class="muted">Η εικόνα δείχνει ενδεικτικά την αρχική και την τελική θέση της άσκησης.</p><div class="modal-actions"><button value="cancel" class="primary">Κλείσιμο</button></div>`)}

$('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';save()};
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='fitplanner-backup-'+todayISO()+'.json';a.click();URL.revokeObjectURL(a.href)};
$('#importInput').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!data.people?.length)throw 0;state=data;save();toast('Το backup εισήχθη')}catch{alert('Το αρχείο backup δεν είναι έγκυρο')}};
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').showModal()}
function closeModal(){$('#modal').close()}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

if('serviceWorker' in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
renderAll();renderCalendar();
